name: efficasante_app
description: Application mobile Efficasante - Gestion clinique et hospitalière (Android & iOS)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^6.0.2
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  local_auth: ^2.3.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
